/*
 * Copyright (C) %%YEAR%% Alexander Borisov
 *
 * Author: Alexander Borisov <borisov@lexbor.com>
 */

/*
 * Caution!
 * This file generated by the script "utils/lexbor/css/names.py"!
 * Do not change this file!
 */


#ifndef LXB_CSS_%%PREFIX%%_RES_H
#define LXB_CSS_%%PREFIX%%_RES_H

#include "lexbor/core/shs.h"
#include "%%CONST_HEADER%%"
#if __has_include("%%STATE_HEADER%%")
    #include "%%STATE_HEADER%%"
#endif


%%SHS_DATA%%

%%SHS%%


#endif /* LXB_CSS_%%PREFIX%%_RES_H */
